<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Country;

class CountrySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
         // Data from CountryCode.org and ISO 3166-1
        $countries = [
            ['name'=>'Afghanistan','iso_codes'=>'AFG','country_code'=>'004','dialing_code'=>'+93'],
            ['name'=>'Åland Islands','iso_codes'=>'ALA','country_code'=>'248','dialing_code'=>'+358'],
            ['name'=>'Albania','iso_codes'=>'ALB','country_code'=>'008','dialing_code'=>'+355'],
            ['name'=>'Algeria','iso_codes'=>'DZA','country_code'=>'012','dialing_code'=>'+213'],
            ['name'=>'American Samoa','iso_codes'=>'ASM','country_code'=>'016','dialing_code'=>'+1-684'],
            ['name'=>'Andorra','iso_codes'=>'AND','country_code'=>'020','dialing_code'=>'+376'],
            ['name'=>'Angola','iso_codes'=>'AGO','country_code'=>'024','dialing_code'=>'+244'],
            ['name'=>'Anguilla','iso_codes'=>'AIA','country_code'=>'660','dialing_code'=>'+1-264'],
            ['name'=>'Antarctica','iso_codes'=>'ATA','country_code'=>'010','dialing_code'=>'+672'],
            ['name'=>'Antigua and Barbuda','iso_codes'=>'ATG','country_code'=>'028','dialing_code'=>'+1-268'],
            ['name'=>'Argentina','iso_codes'=>'ARG','country_code'=>'032','dialing_code'=>'+54'],
            ['name'=>'Armenia','iso_codes'=>'ARM','country_code'=>'051','dialing_code'=>'+374'],
            ['name'=>'Aruba','iso_codes'=>'ABW','country_code'=>'533','dialing_code'=>'+297'],
            ['name'=>'Australia','iso_codes'=>'AUS','country_code'=>'036','dialing_code'=>'+61'],
            ['name'=>'Austria','iso_codes'=>'AUT','country_code'=>'040','dialing_code'=>'+43'],
            ['name'=>'Azerbaijan','iso_codes'=>'AZE','country_code'=>'031','dialing_code'=>'+994'],
            ['name'=>'Bahamas','iso_codes'=>'BHS','country_code'=>'044','dialing_code'=>'+1-242'],
            ['name'=>'Bahrain','iso_codes'=>'BHR','country_code'=>'048','dialing_code'=>'+973'],
            ['name'=>'Bangladesh','iso_codes'=>'BGD','country_code'=>'050','dialing_code'=>'+880'],
            ['name'=>'Barbados','iso_codes'=>'BRB','country_code'=>'052','dialing_code'=>'+1-246'],
            ['name'=>'Belarus','iso_codes'=>'BLR','country_code'=>'112','dialing_code'=>'+375'],
            ['name'=>'Belgium','iso_codes'=>'BEL','country_code'=>'056','dialing_code'=>'+32'],
            ['name'=>'Belize','iso_codes'=>'BLZ','country_code'=>'084','dialing_code'=>'+501'],
            ['name'=>'Benin','iso_codes'=>'BEN','country_code'=>'204','dialing_code'=>'+229'],
            ['name'=>'Bermuda','iso_codes'=>'BMU','country_code'=>'060','dialing_code'=>'+1-441'],
            ['name'=>'Bhutan','iso_codes'=>'BTN','country_code'=>'064','dialing_code'=>'+975'],
            ['name'=>'Bolivia (Plurinational State of)','iso_codes'=>'BOL','country_code'=>'068','dialing_code'=>'+591'],
            ['name'=>'Bonaire, Sint Eustatius and Saba','iso_codes'=>'BES','country_code'=>'535','dialing_code'=>'+599'],
            ['name'=>'Bosnia and Herzegovina','iso_codes'=>'BIH','country_code'=>'070','dialing_code'=>'+387'],
            ['name'=>'Botswana','iso_codes'=>'BWA','country_code'=>'072','dialing_code'=>'+267'],
            ['name'=>'Bouvet Island','iso_codes'=>'BVT','country_code'=>'074','dialing_code'=>'+'],
            ['name'=>'Brazil','iso_codes'=>'BRA','country_code'=>'076','dialing_code'=>'+55'],
            ['name'=>'British Indian Ocean Territory','iso_codes'=>'IOT','country_code'=>'086','dialing_code'=>'+246'],
            ['name'=>'Brunei Darussalam','iso_codes'=>'BRN','country_code'=>'096','dialing_code'=>'+673'],
            ['name'=>'Bulgaria','iso_codes'=>'BGR','country_code'=>'100','dialing_code'=>'+359'],
            ['name'=>'Burkina Faso','iso_codes'=>'BFA','country_code'=>'854','dialing_code'=>'+226'],
            ['name'=>'Burundi','iso_codes'=>'BDI','country_code'=>'108','dialing_code'=>'+257'],
            ['name'=>'Cabo Verde','iso_codes'=>'CPV','country_code'=>'132','dialing_code'=>'+238'],
            ['name'=>'Cambodia','iso_codes'=>'KHM','country_code'=>'116','dialing_code'=>'+855'],
            ['name'=>'Cameroon','iso_codes'=>'CMR','country_code'=>'120','dialing_code'=>'+237'],
            ['name'=>'Canada','iso_codes'=>'CAN','country_code'=>'124','dialing_code'=>'+1'],
            ['name'=>'Cayman Islands','iso_codes'=>'CYM','country_code'=>'136','dialing_code'=>'+1-345'],
            ['name'=>'Central African Republic','iso_codes'=>'CAF','country_code'=>'140','dialing_code'=>'+236'],
            ['name'=>'Chad','iso_codes'=>'TCD','country_code'=>'148','dialing_code'=>'+235'],
            ['name'=>'Chile','iso_codes'=>'CHL','country_code'=>'152','dialing_code'=>'+56'],
            ['name'=>'China','iso_codes'=>'CHN','country_code'=>'156','dialing_code'=>'+86'],
            ['name'=>'Christmas Island','iso_codes'=>'CXR','country_code'=>'162','dialing_code'=>'+61'],
            ['name'=>'Cocos (Keeling) Islands','iso_codes'=>'CCK','country_code'=>'166','dialing_code'=>'+61'],
            ['name'=>'Colombia','iso_codes'=>'COL','country_code'=>'170','dialing_code'=>'+57'],
            ['name'=>'Comoros','iso_codes'=>'COM','country_code'=>'174','dialing_code'=>'+269'],
            ['name'=>'Congo','iso_codes'=>'COG','country_code'=>'178','dialing_code'=>'+242'],
            ['name'=>'Congo, Democratic Republic of the','iso_codes'=>'COD','country_code'=>'180','dialing_code'=>'+243'],
            ['name'=>'Cook Islands','iso_codes'=>'COK','country_code'=>'184','dialing_code'=>'+682'],
            ['name'=>'Costa Rica','iso_codes'=>'CRI','country_code'=>'188','dialing_code'=>'+506'],
            ['name'=>"Côte d'Ivoire",'iso_codes'=>'CIV','country_code'=>'384','dialing_code'=>'+225'],
            ['name'=>'Croatia','iso_codes'=>'HRV','country_code'=>'191','dialing_code'=>'+385'],
            ['name'=>'Cuba','iso_codes'=>'CUB','country_code'=>'192','dialing_code'=>'+53'],
            ['name'=>'Curaçao','iso_codes'=>'CUW','country_code'=>'531','dialing_code'=>'+599'],
            ['name'=>'Cyprus','iso_codes'=>'CYP','country_code'=>'196','dialing_code'=>'+357'],
            ['name'=>'Czechia','iso_codes'=>'CZE','country_code'=>'203','dialing_code'=>'+420'],
            ['name'=>'Denmark','iso_codes'=>'DNK','country_code'=>'208','dialing_code'=>'+45'],
            ['name'=>'Djibouti','iso_codes'=>'DJI','country_code'=>'262','dialing_code'=>'+253'],
            ['name'=>'Dominica','iso_codes'=>'DMA','country_code'=>'212','dialing_code'=>'+1-767'],
            ['name'=>'Dominican Republic','iso_codes'=>'DOM','country_code'=>'214','dialing_code'=>'+1-809'],
            ['name'=>'Ecuador','iso_codes'=>'ECU','country_code'=>'218','dialing_code'=>'+593'],
            ['name'=>'Egypt','iso_codes'=>'EGY','country_code'=>'818','dialing_code'=>'+20'],
            ['name'=>'El Salvador','iso_codes'=>'SLV','country_code'=>'222','dialing_code'=>'+503'],
            ['name'=>'Equatorial Guinea','iso_codes'=>'GNQ','country_code'=>'226','dialing_code'=>'+240'],
            ['name'=>'Eritrea','iso_codes'=>'ERI','country_code'=>'232','dialing_code'=>'+291'],
            ['name'=>'Estonia','iso_codes'=>'EST','country_code'=>'233','dialing_code'=>'+372'],
            ['name'=>'Eswatini','iso_codes'=>'SWZ','country_code'=>'748','dialing_code'=>'+268'],
            ['name'=>'Ethiopia','iso_codes'=>'ETH','country_code'=>'231','dialing_code'=>'+251'],
            ['name'=>'Falkland Islands (Malvinas)','iso_codes'=>'FLK','country_code'=>'238','dialing_code'=>'+500'],
            ['name'=>'Faroe Islands','iso_codes'=>'FRO','country_code'=>'234','dialing_code'=>'+298'],
            ['name'=>'Fiji','iso_codes'=>'FJI','country_code'=>'242','dialing_code'=>'+679'],
            ['name'=>'Finland','iso_codes'=>'FIN','country_code'=>'246','dialing_code'=>'+358'],
            ['name'=>'France','iso_codes'=>'FRA','country_code'=>'250','dialing_code'=>'+33'],
            ['name'=>'French Guiana','iso_codes'=>'GUF','country_code'=>'254','dialing_code'=>'+594'],
            ['name'=>'French Polynesia','iso_codes'=>'PYF','country_code'=>'258','dialing_code'=>'+689'],
            ['name'=>'French Southern Territories','iso_codes'=>'ATF','country_code'=>'260','dialing_code'=>'+'],
            ['name'=>'Gabon','iso_codes'=>'GAB','country_code'=>'266','dialing_code'=>'+241'],
            ['name'=>'Gambia','iso_codes'=>'GMB','country_code'=>'270','dialing_code'=>'+220'],
            ['name'=>'Georgia','iso_codes'=>'GEO','country_code'=>'268','dialing_code'=>'+995'],
            ['name'=>'Germany','iso_codes'=>'DEU','country_code'=>'276','dialing_code'=>'+49'],
            ['name'=>'Ghana','iso_codes'=>'GHA','country_code'=>'288','dialing_code'=>'+233'],
            ['name'=>'Gibraltar','iso_codes'=>'GIB','country_code'=>'292','dialing_code'=>'+350'],
            ['name'=>'Greece','iso_codes'=>'GRC','country_code'=>'300','dialing_code'=>'+30'],
            ['name'=>'Greenland','iso_codes'=>'GRL','country_code'=>'304','dialing_code'=>'+299'],
            ['name'=>'Grenada','iso_codes'=>'GRD','country_code'=>'308','dialing_code'=>'+1-473'],
            ['name'=>'Guadeloupe','iso_codes'=>'GLP','country_code'=>'312','dialing_code'=>'+590'],
            ['name'=>'Guam','iso_codes'=>'GUM','country_code'=>'316','dialing_code'=>'+1-671'],
            ['name'=>'Guatemala','iso_codes'=>'GTM','country_code'=>'320','dialing_code'=>'+502'],
            ['name'=>'Guernsey','iso_codes'=>'GGY','country_code'=>'831','dialing_code'=>'+44-1481'],
            ['name'=>'Guinea','iso_codes'=>'GIN','country_code'=>'324','dialing_code'=>'+224'],
            ['name'=>'Guinea-Bissau','iso_codes'=>'GNB','country_code'=>'624','dialing_code'=>'+245'],
            ['name'=>'Guyana','iso_codes'=>'GUY','country_code'=>'328','dialing_code'=>'+592'],
            ['name'=>'Haiti','iso_codes'=>'HTI','country_code'=>'332','dialing_code'=>'+509'],
            ['name'=>'Heard Island and McDonald Islands','iso_codes'=>'HMD','country_code'=>'334','dialing_code'=>'+672'],
            ['name'=>'Holy See','iso_codes'=>'VAT','country_code'=>'336','dialing_code'=>'+379'],
            ['name'=>'Honduras','iso_codes'=>'HND','country_code'=>'340','dialing_code'=>'+504'],
            ['name'=>'Hong Kong','iso_codes'=>'HKG','country_code'=>'344','dialing_code'=>'+852'],
            ['name'=>'Hungary','iso_codes'=>'HUN','country_code'=>'348','dialing_code'=>'+36'],
            ['name'=>'Iceland','iso_codes'=>'ISL','country_code'=>'352','dialing_code'=>'+354'],
            ['name'=>'India','iso_codes'=>'IND','country_code'=>'356','dialing_code'=>'+91'],
            ['name'=>'Indonesia','iso_codes'=>'IDN','country_code'=>'360','dialing_code'=>'+62'],
            ['name'=>'Iran (Islamic Republic of)','iso_codes'=>'IRN','country_code'=>'364','dialing_code'=>'+98'],
            ['name'=>'Iraq','iso_codes'=>'IRQ','country_code'=>'368','dialing_code'=>'+964'],
            ['name'=>'Ireland','iso_codes'=>'IRL','country_code'=>'372','dialing_code'=>'+353'],
            ['name'=>'Isle of Man','iso_codes'=>'IMN','country_code'=>'833','dialing_code'=>'+44-1624'],
            ['name'=>'Israel','iso_codes'=>'ISR','country_code'=>'376','dialing_code'=>'+972'],
            ['name'=>'Italy','iso_codes'=>'ITA','country_code'=>'380','dialing_code'=>'+39'],
            ['name'=>'Jamaica','iso_codes'=>'JAM','country_code'=>'388','dialing_code'=>'+1-876'],
            ['name'=>'Japan','iso_codes'=>'JPN','country_code'=>'392','dialing_code'=>'+81'],
            ['name'=>'Jersey','iso_codes'=>'JEY','country_code'=>'832','dialing_code'=>'+44-1534'],
            ['name'=>'Jordan','iso_codes'=>'JOR','country_code'=>'400','dialing_code'=>'+962'],
            ['name'=>'Kazakhstan','iso_codes'=>'KAZ','country_code'=>'398','dialing_code'=>'+7'],
            ['name'=>'Kenya','iso_codes'=>'KEN','country_code'=>'404','dialing_code'=>'+254'],
            ['name'=>'Kiribati','iso_codes'=>'KIR','country_code'=>'296','dialing_code'=>'+686'],
            ['name'=>'Korea (Democratic People’s Republic of)','iso_codes'=>'PRK','country_code'=>'408','dialing_code'=>'+850'],
            ['name'=>'Korea (Republic of)','iso_codes'=>'KOR','country_code'=>'410','dialing_code'=>'+82'],
            ['name'=>'Kuwait','iso_codes'=>'KWT','country_code'=>'414','dialing_code'=>'+965'],
            ['name'=>'Kyrgyzstan','iso_codes'=>'KGZ','country_code'=>'417','dialing_code'=>'+996'],
            ['name'=>'Lao People’s Democratic Republic','iso_codes'=>'LAO','country_code'=>'418','dialing_code'=>'+856'],
            ['name'=>'Latvia','iso_codes'=>'LVA','country_code'=>'428','dialing_code'=>'+371'],
            ['name'=>'Lebanon','iso_codes'=>'LBN','country_code'=>'422','dialing_code'=>'+961'],
            ['name'=>'Lesotho','iso_codes'=>'LSO','country_code'=>'426','dialing_code'=>'+266'],
            ['name'=>'Liberia','iso_codes'=>'LBR','country_code'=>'430','dialing_code'=>'+231'],
            ['name'=>'Libya','iso_codes'=>'LBY','country_code'=>'434','dialing_code'=>'+218'],
            ['name'=>'Liechtenstein','iso_codes'=>'LIE','country_code'=>'438','dialing_code'=>'+423'],
            ['name'=>'Lithuania','iso_codes'=>'LTU','country_code'=>'440','dialing_code'=>'+370'],
            ['name'=>'Luxembourg','iso_codes'=>'LUX','country_code'=>'442','dialing_code'=>'+352'],
            ['name'=>'Macao','iso_codes'=>'MAC','country_code'=>'446','dialing_code'=>'+853'],
            ['name'=>'Madagascar','iso_codes'=>'MDG','country_code'=>'450','dialing_code'=>'+261'],
            ['name'=>'Malawi','iso_codes'=>'MWI','country_code'=>'454','dialing_code'=>'+265'],
            ['name'=>'Malaysia','iso_codes'=>'MYS','country_code'=>'458','dialing_code'=>'+60'],
            ['name'=>'Maldives','iso_codes'=>'MDV','country_code'=>'462','dialing_code'=>'+960'],
            ['name'=>'Mali','iso_codes'=>'MLI','country_code'=>'466','dialing_code'=>'+223'],
            ['name'=>'Malta','iso_codes'=>'MLT','country_code'=>'470','dialing_code'=>'+356'],
            ['name'=>'Marshall Islands','iso_codes'=>'MHL','country_code'=>'584','dialing_code'=>'+692'],
            ['name'=>'Martinique','iso_codes'=>'MTQ','country_code'=>'474','dialing_code'=>'+596'],
            ['name'=>'Mauritania','iso_codes'=>'MRT','country_code'=>'478','dialing_code'=>'+222'],
            ['name'=>'Mauritius','iso_codes'=>'MUS','country_code'=>'480','dialing_code'=>'+230'],
            ['name'=>'Mayotte','iso_codes'=>'MYT','country_code'=>'175','dialing_code'=>'+262'],
            ['name'=>'Mexico','iso_codes'=>'MEX','country_code'=>'484','dialing_code'=>'+52'],
            ['name'=>'Micronesia (Federated States of)','iso_codes'=>'FSM','country_code'=>'583','dialing_code'=>'+691'],
            ['name'=>'Moldova (Republic of)','iso_codes'=>'MDA','country_code'=>'498','dialing_code'=>'+373'],
            ['name'=>'Monaco','iso_codes'=>'MCO','country_code'=>'492','dialing_code'=>'+377'],
            ['name'=>'Mongolia','iso_codes'=>'MNG','country_code'=>'496','dialing_code'=>'+976'],
            ['name'=>'Montenegro','iso_codes'=>'MNE','country_code'=>'499','dialing_code'=>'+382'],
            ['name'=>'Montserrat','iso_codes'=>'MSR','country_code'=>'500','dialing_code'=>'+1-664'],
            ['name'=>'Morocco','iso_codes'=>'MAR','country_code'=>'504','dialing_code'=>'+212'],
            ['name'=>'Mozambique','iso_codes'=>'MOZ','country_code'=>'508','dialing_code'=>'+258'],
            ['name'=>'Myanmar','iso_codes'=>'MMR','country_code'=>'104','dialing_code'=>'+95'],
            ['name'=>'Namibia','iso_codes'=>'NAM','country_code'=>'516','dialing_code'=>'+264'],
            ['name'=>'Nauru','iso_codes'=>'NRU','country_code'=>'520','dialing_code'=>'+674'],
            ['name'=>'Nepal','iso_codes'=>'NPL','country_code'=>'524','dialing_code'=>'+977'],
            ['name'=>'Netherlands','iso_codes'=>'NLD','country_code'=>'528','dialing_code'=>'+31'],
            ['name'=>'New Caledonia','iso_codes'=>'NCL','country_code'=>'540','dialing_code'=>'+687'],
            ['name'=>'New Zealand','iso_codes'=>'NZL','country_code'=>'554','dialing_code'=>'+64'],
            ['name'=>'Nicaragua','iso_codes'=>'NIC','country_code'=>'558','dialing_code'=>'+505'],
            ['name'=>'Niger','iso_codes'=>'NER','country_code'=>'562','dialing_code'=>'+227'],
            ['name'=>'Nigeria','iso_codes'=>'NGA','country_code'=>'566','dialing_code'=>'+234'],
            ['name'=>'Niue','iso_codes'=>'NIU','country_code'=>'570','dialing_code'=>'+683'],
            ['name'=>'Norfolk Island','iso_codes'=>'NFK','country_code'=>'574','dialing_code'=>'+672'],
            ['name'=>'Northern Mariana Islands','iso_codes'=>'MNP','country_code'=>'580','dialing_code'=>'+1-670'],
            ['name'=>'Norway','iso_codes'=>'NOR','country_code'=>'578','dialing_code'=>'+47'],
            ['name'=>'Oman','iso_codes'=>'OMN','country_code'=>'512','dialing_code'=>'+968'],
            ['name'=>'Pakistan','iso_codes'=>'PAK','country_code'=>'586','dialing_code'=>'+92'],
            ['name'=>'Palau','iso_codes'=>'PLW','country_code'=>'585','dialing_code'=>'+680'],
            ['name'=>'Panama','iso_codes'=>'PAN','country_code'=>'591','dialing_code'=>'+507'],
            ['name'=>'Papua New Guinea','iso_codes'=>'PNG','country_code'=>'598','dialing_code'=>'+675'],
            ['name'=>'Paraguay','iso_codes'=>'PRY','country_code'=>'600','dialing_code'=>'+595'],
            ['name'=>'Peru','iso_codes'=>'PER','country_code'=>'604','dialing_code'=>'+51'],
            ['name'=>'Philippines','iso_codes'=>'PHL','country_code'=>'608','dialing_code'=>'+63'],
            ['name'=>'Pitcairn','iso_codes'=>'PCN','country_code'=>'612','dialing_code'=>'+64'],
            ['name'=>'Poland','iso_codes'=>'POL','country_code'=>'616','dialing_code'=>'+48'],
            ['name'=>'Portugal','iso_codes'=>'PRT','country_code'=>'620','dialing_code'=>'+351'],
            ['name'=>'Puerto Rico','iso_codes'=>'PRI','country_code'=>'630','dialing_code'=>'+1-787'],
            ['name'=>'Qatar','iso_codes'=>'QAT','country_code'=>'634','dialing_code'=>'+974'],
            ['name'=>'Réunion','iso_codes'=>'REU','country_code'=>'638','dialing_code'=>'+262'],
            ['name'=>'Romania','iso_codes'=>'ROU','country_code'=>'642','dialing_code'=>'+40'],
            ['name'=>'Russian Federation','iso_codes'=>'RUS','country_code'=>'643','dialing_code'=>'+7'],
            ['name'=>'Rwanda','iso_codes'=>'RWA','country_code'=>'646','dialing_code'=>'+250'],
            ['name'=>'Saint Barthélemy','iso_codes'=>'BLM','country_code'=>'652','dialing_code'=>'+590'],
            ['name'=>'Saint Helena, Ascension and Tristan da Cunha','iso_codes'=>'SHN','country_code'=>'654','dialing_code'=>'+290'],
            ['name'=>'Saint Kitts and Nevis','iso_codes'=>'KNA','country_code'=>'659','dialing_code'=>'+1-869'],
            ['name'=>'Saint Lucia','iso_codes'=>'LCA','country_code'=>'662','dialing_code'=>'+1-758'],
            ['name'=>'Saint Martin (French part)','iso_codes'=>'MAF','country_code'=>'663','dialing_code'=>'+590'],
            ['name'=>'Saint Pierre and Miquelon','iso_codes'=>'SPM','country_code'=>'666','dialing_code'=>'+508'],
            ['name'=>'Saint Vincent and the Grenadines','iso_codes'=>'VCT','country_code'=>'670','dialing_code'=>'+1-784'],
            ['name'=>'Samoa','iso_codes'=>'WSM','country_code'=>'882','dialing_code'=>'+685'],
            ['name'=>'San Marino','iso_codes'=>'SMR','country_code'=>'674','dialing_code'=>'+378'],
            ['name'=>'Sao Tome and Principe','iso_codes'=>'STP','country_code'=>'678','dialing_code'=>'+239'],
            ['name'=>'Saudi Arabia','iso_codes'=>'SAU','country_code'=>'682','dialing_code'=>'+966'],
            ['name'=>'Senegal','iso_codes'=>'SEN','country_code'=>'686','dialing_code'=>'+221'],
            ['name'=>'Serbia','iso_codes'=>'SRB','country_code'=>'688','dialing_code'=>'+381'],
            ['name'=>'Seychelles','iso_codes'=>'SYC','country_code'=>'690','dialing_code'=>'+248'],
            ['name'=>'Sierra Leone','iso_codes'=>'SLE','country_code'=>'694','dialing_code'=>'+232'],
            ['name'=>'Singapore','iso_codes'=>'SGP','country_code'=>'702','dialing_code'=>'+65'],
            ['name'=>'Sint Maarten (Dutch part)','iso_codes'=>'SXM','country_code'=>'534','dialing_code'=>'+1-721'],
            ['name'=>'Slovakia','iso_codes'=>'SVK','country_code'=>'703','dialing_code'=>'+421'],
            ['name'=>'Slovenia','iso_codes'=>'SVN','country_code'=>'705','dialing_code'=>'+386'],
            ['name'=>'Solomon Islands','iso_codes'=>'SLB','country_code'=>'090','dialing_code'=>'+677'],
            ['name'=>'Somalia','iso_codes'=>'SOM','country_code'=>'706','dialing_code'=>'+252'],
            ['name'=>'South Africa','iso_codes'=>'ZAF','country_code'=>'710','dialing_code'=>'+27'],
            ['name'=>'South Georgia and the South Sandwich Islands','iso_codes'=>'SGS','country_code'=>'239','dialing_code'=>'+500'],
            ['name'=>'South Sudan','iso_codes'=>'SSD','country_code'=>'728','dialing_code'=>'+211'],
            ['name'=>'Spain','iso_codes'=>'ESP','country_code'=>'724','dialing_code'=>'+34'],
            ['name'=>'Sri Lanka','iso_codes'=>'LKA','country_code'=>'144','dialing_code'=>'+94'],
            ['name'=>'Sudan','iso_codes'=>'SDN','country_code'=>'729','dialing_code'=>'+249'],
            ['name'=>'Suriname','iso_codes'=>'SUR','country_code'=>'740','dialing_code'=>'+597'],
            ['name'=>'Svalbard and Jan Mayen','iso_codes'=>'SJM','country_code'=>'744','dialing_code'=>'+47'],
            ['name'=>'Sweden','iso_codes'=>'SWE','country_code'=>'752','dialing_code'=>'+46'],
            ['name'=>'Switzerland','iso_codes'=>'CHE','country_code'=>'756','dialing_code'=>'+41'],
            ['name'=>'Syrian Arab Republic','iso_codes'=>'SYR','country_code'=>'760','dialing_code'=>'+963'],
            ['name'=>'Taiwan, Province of China','iso_codes'=>'TWN','country_code'=>'158','dialing_code'=>'+886'],
            ['name'=>'Tajikistan','iso_codes'=>'TJK','country_code'=>'762','dialing_code'=>'+992'],
            ['name'=>'Tanzania, United Republic of','iso_codes'=>'TZA','country_code'=>'834','dialing_code'=>'+255'],
            ['name'=>'Thailand','iso_codes'=>'THA','country_code'=>'764','dialing_code'=>'+66'],
            ['name'=>'Timor-Leste','iso_codes'=>'TLS','country_code'=>'626','dialing_code'=>'+670'],
            ['name'=>'Togo','iso_codes'=>'TGO','country_code'=>'768','dialing_code'=>'+228'],
            ['name'=>'Tokelau','iso_codes'=>'TKL','country_code'=>'772','dialing_code'=>'+690'],
            ['name'=>'Tonga','iso_codes'=>'TON','country_code'=>'776','dialing_code'=>'+676'],
            ['name'=>'Trinidad and Tobago','iso_codes'=>'TTO','country_code'=>'780','dialing_code'=>'+1-868'],
            ['name'=>'Tunisia','iso_codes'=>'TUN','country_code'=>'788','dialing_code'=>'+216'],
            ['name'=>'Turkey','iso_codes'=>'TUR','country_code'=>'792','dialing_code'=>'+90'],
            ['name'=>'Turkmenistan','iso_codes'=>'TKM','country_code'=>'795','dialing_code'=>'+993'],
            ['name'=>'Tuvalu','iso_codes'=>'TUV','country_code'=>'798','dialing_code'=>'+688'],
            ['name'=>'Uganda','iso_codes'=>'UGA','country_code'=>'800','dialing_code'=>'+256'],
            ['name'=>'Ukraine','iso_codes'=>'UKR','country_code'=>'804','dialing_code'=>'+380'],
            ['name'=>'United Arab Emirates','iso_codes'=>'ARE','country_code'=>'784','dialing_code'=>'+971'],
            ['name'=>'United Kingdom of Great Britain and Northern Ireland','iso_codes'=>'GBR','country_code'=>'826','dialing_code'=>'+44'],
            ['name'=>'United States of America','iso_codes'=>'USA','country_code'=>'840','dialing_code'=>'+1'],
            ['name'=>'Uruguay','iso_codes'=>'URY','country_code'=>'858','dialing_code'=>'+598'],
            ['name'=>'Uzbekistan','iso_codes'=>'UZB','country_code'=>'860','dialing_code'=>'+998'],
            ['name'=>'Vanuatu','iso_codes'=>'VUT','country_code'=>'548','dialing_code'=>'+678'],
            ['name'=>'Venezuela (Bolivarian Republic of)','iso_codes'=>'VEN','country_code'=>'862','dialing_code'=>'+58'],
            ['name'=>'Viet Nam','iso_codes'=>'VNM','country_code'=>'704','dialing_code'=>'+84'],
            ['name'=>'Wallis and Futuna','iso_codes'=>'WLF','country_code'=>'876','dialing_code'=>'+681'],
            ['name'=>'Western Sahara','iso_codes'=>'ESH','country_code'=>'732','dialing_code'=>'+212'],
            ['name'=>'Yemen','iso_codes'=>'YEM','country_code'=>'887','dialing_code'=>'+967'],
            ['name'=>'Zambia','iso_codes'=>'ZMB','country_code'=>'894','dialing_code'=>'+260'],
            ['name'=>'Zimbabwe','iso_codes'=>'ZWE','country_code'=>'716','dialing_code'=>'+263'],
        ];

        foreach ($countries as $data) {
            Country::updateOrCreate(
                ['iso_codes' => $data['iso_codes']],
                [
                    'name'         => $data['name'],
                    'country_code'=> $data['country_code'],
                    'dialing_code'=> $data['dialing_code'],
                ]
            );
        }
    }
}
